package constants

//SQL ENV
const (
	ENV_SQL_DRIVER   = "CRAWLAB_SQL_DRIVER"
	ENV_SQL_HOST     = "CRAWLAB_SQL_HOST"
	ENV_SQL_PORT     = "CRAWLAB_SQL_PORT"
	ENV_SQL_USERNAME = "CRAWLAB_SQL_USERNAME"
	ENV_SQL_PASSWORD = "CRAWLAB_SQL_PASSWORD"
)

//Mongo ENV
const (
	ENV_MONGO_HOST           = "CRAWLAB_MONGO_HOST"
	ENV_MONGO_PORT           = "CRAWLAB_MONGO_PORT"
	ENV_MONGO_USERNAME       = "CRAWLAB_MONGO_USERNAME"
	ENV_MONGO_PASSWORD       = "CRAWLAB_MONGO_PASSWORD"
	ENV_MONGO_AUTH_SOURCE    = "CRAWLAB_MONGO_AUTH_SOURCE"
	ENV_MONGO_AUTH_MECHANISM = "CRAWLAB_MONGO_AUTH_MECHANISM"
)

//REDIS ENV
const (
	ENV_REDIS_HOST     = "CRAWLAB_REDIS_HOST"
	ENV_REDIS_PORT     = "CRAWLAB_REDIS_PORT"
	ENV_REDIS_USERNAME = "CRAWLAB_REDIS_USERNAME"
	ENV_REDIS_PASSWORD = "CRAWLAB_REDIS_PASSWORD"
)

//FS ENV
const (
	ENV_SEAWEED_FS_FILER_URL= "CRAWLAB_FS_FILER_URL"
)

const (
	KEY_SQL_DRIVER_MYSQL    = "mysql"
	KEY_SQL_DRIVER_POSTGRES = "postgres"

	KEY_DATA_SOURCE_NAME_MONGO    = "mongodb://%s:%s"
	KEY_DATA_SOURCE_NAME_MYSQL    = "%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local"
	KEY_DATA_SOURCE_NAME_POSTGRES = "user=%s password=%s host=%s port=%s dbname=%s sslmode=disable TimeZone=Asia/Shanghai"

	KEY_SEAWEED_FS_FILE_LIST_JSON = "%s?pretty=y"
	KEY_SEAWEED_FS_FILE_INFO_JSON = "%s?metadata=true&pretty=yes"
)


